### PR TITLE
USM Implementation

### PR DESCRIPTION
**Pull request by isaacault**
Implement USM functionality into SYCL-BLAS which can be enabled with cmake configuration flag.

### CODE REVIEW

**Comment by isaacault** [comment]
@ProGTX requesting you as potential reviewer. Still a WIP as waiting on some ComputeCPP functionality but will be looking to get this checked in once it can pass the workflow checks

**Comment by Bensuo** [comment]
That is a lot of `#ifdef`s to be adding throughout the codebase. I understand this is probably the simplest route to a working USM implementation but is this really something we want to be committing to? I feel like this is introducing a lot of technical debt and is going to hurt maintainability in the long run.

**Comment by Rbiessy** [comment]
What is the status on this MR? Do we want to use USM in SYCL-BLAS? The changes look scary, I'd rather not merge this to master if possible.

**Comment by mehdi-goli** [comment]
Closing this PR as it is not relevant at this stage.

**Pull request closed without merging**
