### PR TITLE
adding forestexpr to fuse independent trees

### PR DESCRIPTION
**Pull request by theoden8**
@josealiaga This is a prototype of expression evaluating multiple independent trees. unfortunately, it only works for 1 tree due to standard layout error, but there should be a workaround.
I.e. this is like JoinExpr with variadic templates which only works for one subexpression.

### CODE REVIEW

**Comment by josealiaga** [comment]
Perfect!! Could you locate and solve the error?

**Comment by theoden8** [comment]
Two things I can't do. First, I need ComputeCpp 031, second, I will need help to fix standard layout problem on tuple of size >1.

**Comment by josealiaga** [comment]
Will you need my help?

**Comment by theoden8** [comment]
I think it will be possible to solve later, when this error is fixed in ComputeCpp.

**Comment by josealiaga** [comment]
Ok. Thank you very much.

**Comment by theoden8** [comment]
@josealiaga, I only pulled from #28, here I'm thinking of how to write something like std::tuple without writing a ton of templated code.

**Pull request closed without merging**
